// <auto-generated />
using System;
using AutomobiliuNuoma.Core.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomobiliuNuoma.Core.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.Automobilis", b =>
                {
                    b.Property<int>("AutomobilisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutomobilisId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NuomosKaina")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AutomobilisId");

                    b.ToTable("Automobilis");

                    b.HasDiscriminator().HasValue("Automobilis");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.Darbuotojas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtliktuUzsakymuKiekis")
                        .HasColumnType("int");

                    b.Property<double>("BazinisAtlyginimas")
                        .HasColumnType("float");

                    b.Property<int>("Pareigos")
                        .HasColumnType("int");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Darbuotojai");
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.Klientas", b =>
                {
                    b.Property<int>("KlientasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KlientasId"));

                    b.Property<DateOnly>("GimimoMetai")
                        .HasColumnType("date");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KlientasId");

                    b.ToTable("Klientai");
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.NuomosUzsakymas", b =>
                {
                    b.Property<int>("UzsakymasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzsakymasId"));

                    b.Property<string>("AutoTipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AutomobilisId")
                        .HasColumnType("int");

                    b.Property<int>("BenzAutomobilisId")
                        .HasColumnType("int");

                    b.Property<int>("DarbuotojasId")
                        .HasColumnType("int");

                    b.Property<int>("DienuKiekis")
                        .HasColumnType("int");

                    b.Property<int>("ElektromobilisId")
                        .HasColumnType("int");

                    b.Property<int>("KlientasId")
                        .HasColumnType("int");

                    b.Property<string>("KlientoPavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KlientoVardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NuomosPradzia")
                        .HasColumnType("datetime2");

                    b.HasKey("UzsakymasId");

                    b.HasIndex("AutomobilisId");

                    b.HasIndex("KlientasId");

                    b.ToTable("NuomosUzsakymas");
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.Elektromobilis", b =>
                {
                    b.HasBaseType("AutomobiliuNuoma.Core.Models.Automobilis");

                    b.Property<int>("BaterijosTalpa")
                        .HasColumnType("int");

                    b.Property<int>("KrovimoLaikas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Elektromobilis");
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.NaftosKuroAutomobilis", b =>
                {
                    b.HasBaseType("AutomobiliuNuoma.Core.Models.Automobilis");

                    b.Property<double>("DegaluSanaudos")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("NaftosKuroAutomobilis");
                });

            modelBuilder.Entity("AutomobiliuNuoma.Core.Models.NuomosUzsakymas", b =>
                {
                    b.HasOne("AutomobiliuNuoma.Core.Models.Automobilis", "NuomuojamasAuto")
                        .WithMany()
                        .HasForeignKey("AutomobilisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomobiliuNuoma.Core.Models.Klientas", "Uzsakovas")
                        .WithMany()
                        .HasForeignKey("KlientasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NuomuojamasAuto");

                    b.Navigation("Uzsakovas");
                });
#pragma warning restore 612, 618
        }
    }
}
